### ISSUE TITLE
BM_colony_SOP01 needs editing

### ISSUE THREAD

**Issue by jamrt** [EllisNZ/VSW-Remaster#2]
This wood pole needs to go, as it sticks out from the window that is placed there. The exterior has the wooden beam end on the top level (the lower lever is all rocks):
![grafik](https://user-images.githubusercontent.com/57233780/132572233-66f3cffb-e80c-411a-8630-aacb6b0215cc.png)

The round bit has the usual problem of bits of the roof from the connector sticking out:
![grafik](https://user-images.githubusercontent.com/57233780/132572404-06b18e86-32ed-4ac3-86de-880c07621b53.png)
Except only halfway
![grafik](https://user-images.githubusercontent.com/57233780/132572465-883291dc-fd5e-4325-92df-0d5bad2ad3df.png)
Any solution other than the current one would be an improvement.

**Comment by Ellnz** [comment]
New model provided.
