### ISSUE TITLE
BM_colony_playerhome01 needs editing

### ISSUE THREAD

**Issue by jamrt** [EllisNZ/VSW-Remaster#4]
This wooden beam needs to go:
![grafik](https://user-images.githubusercontent.com/57233780/132574835-c4a6c4b1-4963-42ac-8e4b-d95ebd6e4adb.png)

The round bit has the usual problem of bits of the roof from the connector sticking out:
![grafik](https://user-images.githubusercontent.com/57233780/132574897-d9ba1e70-b36c-46a6-88f4-5fa102554c72.png)

Except only halfway.
![grafik](https://user-images.githubusercontent.com/57233780/132574943-6cb1b0d9-ef56-4fee-842d-862d1e8460d6.png)

This needs change of some kind.

**Comment by Ellnz** [comment]
New mesh provided
