### ISSUE TITLE
Releases page isn't clear

### ISSUE THREAD

**Issue by AnyOldName3** [EllisNZ/VSW-Remaster#6]
I've just had a conversation with a couple of users who'd clicked the source code zip link instead of the intended download link and found it hadn't been detected as a BAIN.

![image](https://user-images.githubusercontent.com/8485112/224406350-3e07cf5b-025d-44d2-9dff-d97933da2776.png)

This could be made more user-friendly by editing the release so the archive was included in the list of assets and clicking the big *Attach binaries by dropping them here or selecting them.* section below the textbox - it looks like the smaller *Attach files by dragging & dropping, selecting or pasting them.* bar at the bottom of the textbox was used instead. That's a pretty easy mistake to make, so if I knew which tracker GitHub used for that kind of thing, I'd complain there, too, as I doubt this is the only repo with the same problem.

**Comment by jamrt** [comment]
Should be clearer now.
